//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFactoryGenerator;

public partial interface ISimpleFactoryBuilder<in TKey, TProduct>
{
    ISimpleFactory<TKey, T1, TProduct> Build<T1>();

    ISimpleFactory<TKey, T1, T2, TProduct> Build<T1, T2>();

    ISimpleFactory<TKey, T1, T2, T3, TProduct> Build<T1, T2, T3>();

    ISimpleFactory<TKey, T1, T2, T3, T4, TProduct> Build<T1, T2, T3, T4>();

    ISimpleFactory<TKey, T1, T2, T3, T4, T5, TProduct> Build<T1, T2, T3, T4, T5>();

    ISimpleFactory<TKey, T1, T2, T3, T4, T5, T6, TProduct> Build<T1, T2, T3, T4, T5, T6>();

    ISimpleFactory<TKey, T1, T2, T3, T4, T5, T6, T7, TProduct> Build<T1, T2, T3, T4, T5, T6, T7>();

    ISimpleFactory<TKey, T1, T2, T3, T4, T5, T6, T7, T8, TProduct> Build<T1, T2, T3, T4, T5, T6, T7, T8>();

}
